services:
  mysql:
    image: 'mysql:8'
    environment:
      MYSQL_DATABASE: ticket
      MYSQL_ROOT_PASSWORD: toor
    ports:
      - "33061:3306"

  app:
    build:
      context: .
    ports:
      - "8082:8082"
    depends_on:
      - mysql
    environment:
      QUEST_DARKORO_TOKEN:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/ticket
    #network_mode: host
